version: '3.3'
services:
  axon-server:
    container_name: fj_axonserver
    image: axoniq/axonserver:latest-jdk-17-dev-nonroot
    hostname: axonserver
    volumes:
      - axon-server-data:/data
      - axon-server-events:/eventdata
      - axon-server-config:/config:ro
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - axon-network

volumes:
  axon-server-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
  axon-server-events:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/events
      o: bind
  axon-server-config:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/config
      o: bind

networks:
  axon-network:
    driver: bridge