version: "3.7"

services:
  discovery-service:
    build:
      context: ../discovery-service
      dockerfile: ./Dockerfile
    env_file: env/develop/discovery.env.develop
    container_name: flyjob_discovery_service
    restart: always
    ports:
      - "8761:8761"
    networks:
      - config-network

  config-service:
    env_file: env/develop/config.env.develop
    build:
      context: ../config-service
      dockerfile: ./Dockerfile
    container_name: flyjob_config_service
    depends_on:
      - discovery-service
    ports:
      - "8012:8012"
    expose:
      - "8012"
    networks:
      - config-network
    restart: on-failure
    links:
      - discovery-service
  #
  #  redis-cache:
  #    image: redis:latest
  #    restart: always
  #    ports:
  #      - '6379:6379'
  #    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  #    volumes:
  #      - cache:/data
  #
  #  minio:
  #    container_name: flyjob_auth_dfs
  #    image: 'bitnami/minio:latest'
  #    ports:
  #      - '9000:9000'
  #      - '9001:9001'
  #    environment:
  #      - MINIO_ROOT_USER=minio-root-user
  #      - MINIO_ROOT_PASSWORD=minio-root-password
  #    networks:
  #      - config-network
  #
  #
#  postgres-db:
#    container_name: flyjob_postgre_db
#    image: postgres
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 123456
#      PGDATA: /data/postgres
#    volumes:
#      - db:/data/postgres
#    ports:
#      - "4445:5432"
#    networks:
#      - config-network
#    restart: unless-stopped

#  auth-service:
#    env_file: env/develop/auth.env.develop
#    build:
#      context: ../auth-service/auth-container
#      dockerfile: ./Dockerfile
#    container_name: flyjob_auth_service
#    depends_on:
#      - config-service
#      - discovery-service
#      - api-gateway
#    links:
#      - discovery-service
#      - config-service
#      - api-gateway
#      - postgres-db
#    networks:
#      - config-network
#    restart: on-failure


#  api-gateway:
#    build:
#      context: ../api-gateway
#      dockerfile: ./Dockerfile
#    container_name: flyjob_api-gateway
#    env_file: env/develop/api-gateway.env.develop
#    ports:
#      - "8082:8082"
#    depends_on:
#      - config-service
#      - discovery-service
#    links:
#      - discovery-service
#      - config-service
#      - postgres-db
#    networks:
#      - config-network
#    restart: on-failure

networks:
  config-network:
    driver: bridge

volumes:
  cache:
    driver: local
  pgadmin:
  db:
    driver: local