spring:
  profiles:
    active: ${PROFILE:pre-develop}
  config:
    fail-fast: true
    retry:
      maxAttempts: 200
      maxInterval: 10000
    import: configserver:http://62.72.45.66:8012
  application:
    name: authorization-service
server:
  servlet:
    context-path: /authorization-context
logging:
  level:
    org.springframework.transaction.interceptor: TRACE
grpc:
  server:
    port: 9091
