version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk
    steps:
      - run:
          name: Install Maven
          command: sudo apt-get install maven
      - checkout
      - run:
          name: Maven Install Jar
          command: maven clean install

workflows:
  version: 2
  build-and-test:
      jobs:
      - build