spring:
  profiles:
    active: ${PROFILE:pre-develop}
  config:
    fail-fast: true
    retry:
      maxAttempts: 200
      maxInterval: 10000
    import: configserver:http://62.72.45.66:8012
  application:
    name: payment-service

  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none

server:
  servlet:
    context-path: /payment-context

logging:
  level:
    org.springframework.transaction.interceptor: TRACE

