server:
  port: ${PORT:0}
spring:
  profiles:
    active: ${PROFILE:develop}
  config:
    fail-fast: true
    retry:
      maxAttempts: 200
      maxInterval: 10000
    import: ${CONFIG_URL:optional:configserver:http://localhost:8012}
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: auth-service
  banner:
    location: classpath:banner.txt
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
