spring:
  profiles:
    active: ${PROFILE:develop}
  config:
    fail-fast: true
    retry:
      maxAttempts: 200
      maxInterval: 10000
    import: configserver:http://localhost:8012
  application:
    name: auth-service
  minio:
    access-key: ${MINIO_ACCESS_KEY:minio-root-user}
    secret-key: ${MINIO_SECRET_KEY:minio-root-password}
    url: ${MINIO_URL:http://localhost:9000}
    bucket: ${MINIO_BUCKET:auth-service}
    region: ${MINIO_REGION:us-east-1}
    enabled: ${MINIO_ENABLED:true}
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 10MB
#      max-request-size: 10MB
#      file-size-threshold: 1MB
  liquibase:
    clear-checksums: false
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
springdoc:
  api-docs:
    path: /api-docs

server:
  servlet:
    context-path: /auth-context

logging:
  level:
    org.springframework.transaction.interceptor: TRACE

test:
  values:
    user:
      uuid: ${TEST_USER:476143fe-c158-4473-a62c-a1cd31a91583}