spring:
  profiles:
    active: ${PROFILE:local}
  config:
    fail-fast: true
    retry:
      maxAttempts: 200
      maxInterval: 10000
    import: configserver:http://localhost:8012
  application:
    name: auth-service

  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
mybatis:
  executor-type: REUSE
  mapper-locations: classpath*:/**/*Mapper.xml
  type-aliases-package: az.rock.flyjob.auth.dataAccess.model.compose
  type-handlers-package: az.rock.flyjob.auth.dataAccess.config.mybatis.handlers
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

server:
  servlet:
    context-path: /auth-context

logging:
  level:
    org.springframework.transaction.interceptor: TRACE

