spring:
  profiles:
    active: ${PROFILE:local}
  config:
    fail-fast: true
    retry:
      maxAttempts: 200
      maxInterval: 10000
    import: configserver:http://localhost:8012
  application:
    name: auth-service

