spring:
  profiles:
    active: ${PROFILE:develop}
  config:
    fail-fast: true
    retry:
      maxAttempts: 200
      maxInterval: 10000
    import: configserver:http://localhost:8012
  application:
    name: auth-service
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
springdoc:
  api-docs:
    path: /api-docs

server:
  servlet:
    context-path: /auth-context