spring:
  profiles:
    active: ${PROFILE:develop}
  config:
    fail-fast: true
    retry:
      maxAttempts: 200
      maxInterval: 10000
    import: configserver:http://localhost:8012
  application:
    name: auth-service
  minio:
    access-key: ${MINIO_ACCESS_KEY:minio-root-user}
    secret-key: ${MINIO_SECRET_KEY:minio-root-password}
    url: ${MINIO_URL:http://localhost:9000}
    bucket: ${MINIO_BUCKET:auth-service}
    region: ${MINIO_REGION:us-east-1}
    enabled: ${MINIO_ENABLED:true}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 1MB
  liquibase:
    clear-checksums: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  api-docs:
    path: /api-docs

server:
  servlet:
    context-path: /auth-context

logging:
  level:
    org.springframework.transaction.interceptor: TRACE

test:
  values:
    user:
      uuid: ${TEST_USER:be27f873-7320-478c-991f-2a1461881fdd}
      username: ${TEST_USERNAME:vugar_mammadli}
      language: ${TEST_LANGUAGE:EN}
      isAnonymous: ${TEST_IS_ANONYMOUS:false}
      isAuthenticated: ${TEST_IS_AUTHONTICATED:true}
      role:
        name: ${TEST_ROLE:ROLE_JOB_SEEKER}