spring:
  profiles:
    active: ${PROFILE:pre-develop}
  config:
    fail-fast: true
    retry:
      maxAttempts: 200
      maxInterval: 10000
    import: configserver:http://62.72.45.66:8012
  application:
    name: job-seeker-service
mybatis:
  config-location: classpath:mybatis-config.xml

server:
  servlet:
    context-path: /js-context
logging:
  level:
    org.springframework.transaction.interceptor: TRACE
