name: CI
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
env:
  REGISTRY: ghcr.io
  REPO_OWNER: ${{ github.repository_owner }}
jobs:
  build:
    strategy:
      matrix:
        image_name: [ "auth-service" ]
    runs-on: ubuntu-latest
    steps:
      - name: Maven Mirror Config Settings
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: '[{"id": "snapshots", "username": "admin", "password": "A123456v"}]'
          mirrors: '[{"id": "nexus", "name": "mirrorName", "mirrorOf": "mirrorOf", "url": "http://62.72.45.66:8081/repository/maven-snapshots/"}]'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build
        working-directory: ${{ matrix.image_name }}
        run: |
          mvn --batch-mode --update-snapshots verify
          mv build/libs/$(ls build/libs) app.jar

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract image metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ matrix.image_name }}
          tags: latest

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.image_name }}
          file: ${{ matrix.image_name }}/Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          secrets: |
            GTOKEN=${{ secrets.GH_TOKEN }}